<?php echo $titulo?>
<table id="tablerol" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Detallar</th>
        </tr>
    </thead>    
    <tbody>
        <?php
        foreach ($datos as $rol){
            ?>
        <tr>
            <td><?php echo $rol->getId()?></td>
            <td><?php echo $rol->getNombre()?></td>
            <td></td>
            
    <a href="#" data-toggle="modal"
       data-target="#verModal<?php echo $rol-> getId()?>">
        <img src="<?php echo $this->basePath().'img/zft-logo'?>"
             alt="" class="img-circle img-responsive" title="Ver Detalle">
    </a>
    
    <div class="modal fade" id="verModal<?php echo $rol->getId()?>"
         dara-backdrop="static" data-keyboard="false"
         draggable="modal-header"
         tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
        
        <div class="modal-dialog">
             <div class="modal-content">
                 <div class="modal-header">
                     <button type="button" class="close"data-dimiss>
                         
                     </button>
                     
                 </div>
                
            </div>
            
        </div>
        
    </div>
            
        </tr>
        <?php
            }
            ?>
    </tbody>
        
    </table>
